UPDATE bank_apps SET valid_lp = 
VALUES (
    'FETCH',
    'Fetch_Bark_Bank',
    'BEST_MOVERS,FRESH_BAG,GOLDEN_HOTELS,HIS_AND_HERS,KINGSMAN_SERVICES,NATIONAL_BANKING,PASSION_PAY,ROYAL_AIR,TAKO_RAMEN,OUTDOOR_BROS,SUSHI_CHOPSTICKS,JOYSPRING_TOYS,GO_CART'
  );